### ISSUE TITLE
Version Tracking

### ISSUE THREAD

**Issue by OudomMunint** [OudomMunint/.NetMAUI-To-Do-List-App#244]
- [x] Use the [IVersionTracking](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.applicationmodel.iversiontracking) interface.
- [x] Show app version in settings page about section.
- [x] Add platform info in the formatted string.
